name: Playwright Tests with Allure Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.52.0
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4

      - name: Setup
        run: |
          npm ci
          mkdir -p allure-results

      - name: Run tests
        run: npx playwright test --workers=1 --reporter=line,allure-playwright
        env:
          CI: true

      - name: Setup Allure
        if: always()
        run: |
          apt-get update && apt-get install -y openjdk-17-jre
          npm install -g allure-commandline

      - name: Generate report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Publish to GitHub Pages
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy Pages
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        id: deployment
        uses: actions/deploy-pages@v4
