name: Playwright Tests with Allure Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Create allure-results directory
        run: mkdir -p allure-results

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright
        env:
          CI: true

      - name: Install Java for Allure
        if: always()
        run: apt-get update && apt-get install -y openjdk-17-jre

      - name: Install allure-commandline
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        run: mkdir -p allure-report && allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report to GitHub Pages
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        id: deployment
        uses: actions/deploy-pages@v4
